name: Teste tag
on:
  push:
    tags:
      - '*.*.*'
    branches-ignore:
      - "teste"
jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python hi.py
