name: Teste tag
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
env:
  TAG: ${{ github.ref_name }}
jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - run: python hi.py

