name: Action 2
on:
  workflow_run:
    workflows: ["release-please"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Fetch tags
          run: git fetch --tags --prune --progress origin

        - name: Get the last tag
          id: get_last_tag
          run: |
           latest_tag=$(git describe --abbrev=0 --tags)
           echo "::set-output name=latest_tag::$latest_tag"

        - name: Print the last tag
          run: echo "The last tag is ${{ steps.get_last_tag.outputs.latest_tag }}"