name: Teste de variaveis
on:
  push:
jobs:
  show-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show VARIAVEL
        run: |
            echo $VARIAVEL
            echo ${{ env.VARIAVEL }}
      - name: VARIAVEL in script
        run: python hi.py
